"""Add remarks field to transactions and money requests

Revision ID: 6dc1cdb222af
Revises: dd7a79998f4b
Create Date: 2025-01-04 22:31:21.868066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc1cdb222af'
down_revision = 'dd7a79998f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_mobile_number', ['mobile_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_mobile_number', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    with op.batch_alter_table('money_request', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
