"""Add dob and profile_picture columns to User model

Revision ID: 74a993232797
Revises: 6dc1cdb222af
Create Date: 2025-01-23 20:12:12.289402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a993232797'
down_revision = '6dc1cdb222af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_account_number', ['account_number'])
        batch_op.create_unique_constraint('uq_customer_id', ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_id', type_='unique')
        batch_op.drop_constraint('uq_account_number', type_='unique')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
